apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-conversao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-conversao
  template:
    metadata:
      labels: 
        app: api-conversao
    spec:
      containers:
        - name: api-conversao
          image: breinerhenrique/api-conversao:v1
          ports:
          - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: api-conversao-service
spec:
  selector:
    app: api-conversao
  ports:
    - port: 80
  type: NodePort
