apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-conversao
spec:
  replicas: 2
  selector:
    matchLabels:
     app: api-conversao
  template:
    metadata:
      labels: 
        app: api-conversao
    spec:
      containers:
        - name: api-conversao
          image: breinerhenrique/api-conversao:v1
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: api-conversao-service
spec:
  selector:
    app: api-conversao
  ports:
    - port: 8080 # porta que roda a aplicação
      nodePort: 30000 # porta exposta do cluster via NodePort
  type: NodePort
